#!/bin/bash

rm gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad -fR
git clone git://anongit.freedesktop.org/gstreamer/gstreamer -b 0.10 --depth=1
git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-base -b 0.10 --depth=1
git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-good -b 0.10 --depth=1
git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-bad -b 0.10 --depth=1

