#!/bin/bash

cd gstreamer
./autogen.sh --enable-poisoning --disable-{loadsave,tests,examples,debug,debugutils,gtk-doc} && make && make install && ldconfig && ldconfig
cd ..

cd gst-plugins-base
./autogen.sh --disable-{gtk-doc,tests,exaxmples,debug,debugutils,orc} && make && make install && ldconfig
cd ..

cd gst-plugins-good
./autogen.sh --disable-{gtk-doc,tests,examples,debug,debugutils} --disable-{apetag,audiofx,auparse,cutter,effectv,interleave,flx,goom,goom2k1,imagefreeze,law,level,matroska,monoscope,multifile,multipart,replaygain,shapewipe,smpte,spectrum,y4m,waveform,oss,oss4,sunaudio,osx_audio,osx_video,x,xshm,aalib,aalibtest,annodex,cairo,cairo_gobject,esd,esdtest,flac,gconf,gdk_pixbuf,jack,jpeg,libcaca,libdv,libpng,dv1394,shout2,soup,taglib,wavpack} && make && make install && ldconfig
cd ..

cd gst-plugins-bad
./autogen.sh --disable-{gtk-doc,tests,examples,debug,debugutils,fatal-warnings} --enable-experimental --disable-{audiovisualizers,bayer,cdxaparse,dccp,dtmf,dvbsuboverlay,dvdspu,faceoverlay,festival,fieldanalysis,freeze,freeverb,frei0r,gaudieffects,geometrictransform,hls,inter,ivfparse,jp2kdecimator,liveadder,mve,mxf,nsf,nuvdemux,patchdetect,pcapparse,pnm,scaletempo,sdi,segmentclip,siren,smooth,speed,subenc,tta,vmnc,y4m,directsound,wasapi,direct3d,directdraw,direct3d9,directshow,android_media,apple_media,osx_video,shm,vcd,opensles,assrender,voamrwbenc,voaacenc,apexsink,cdaudio,celt,chromaprint,cog,dc1394,decklink,wayland,dirac,dts,resindvd,faac,faad,flite,gsm,jp2k,liveadder,ladspa,lv2,libmms,linsys,modplug,mimic,mplex,musepack,musicbrainz,mythtv,nas,neon,ofa,openal,opencv,opus,pvr,rsvg,eglgles,timidity,teletextdec,wildmidi,sdl,sdltest,sndfile,soundtouch,spc,gme,vp8,swfdec,dvb,wininet,acm,vdpau,schro,zbar,spandsp,gsettings,schemas-compile,sndio} && make && make install && ldconfig
cd ..

cd gst-omx
./autogen --disable-{gtk-doc,tests,examples,debug,debugutils,fatal-warnings} && make && make install && ldconfig
cd ..

#halt
