#!/bin/bash

apt-get remove gstreamer0.10*

cd gstreamer
make install
cd ..

cd gst-plugins-base
make install
cd ..

cd gst-plugins-good
make install
cd ..

cd gst-plugins-bad
make install
cd ..

cd gst-omx
make install
cd ..
