#!/bin/bash

for archive in gstreamer-1.0.6.tar.xz gst-plugins-base-1.0.6.tar.xz gst-plugins-good-1.0.6.tar.xz gst-plugins-bad-1.0.6.tar.xz gst-omx-1.0.0.tar.xz; do
	tar -xJf $archive
done

mv gstreamer-1.0.6 gstreamer
mv gst-plugins-base-1.0.6 gst-plugins-base
mv gst-plugins-good-1.0.6 gst-plugins-good
mv gst-plugins-bad-1.0.6 gst-plugins-bad
mv gst-omx-1.0.0 gst-omx

#git clone git://anongit.freedesktop.org/gstreamer/gst-omx -b master --depth=1

#wget https://raw.github.com/raspberrypi/firmware/master/opt/vc/include/IL/OMX_Broadcom.h -O gst-omx/OMX_Broadcom.h
